### ISSUE TITLE
AstroMenaceCheat Patch is broken: request for an other patch for stable version 1.3.2

### ISSUE THREAD

**Issue by landscape69** [richelbilderbeek/astro_menace_cheat#1]
patch seem to be broken:

A    MacOSX.zip
A    ReadMe.txt
A    CMakeLists.txt
A    astromenace_64.png
A    astromenace_128.png
A    gpl-3.0.txt
 U   .
Checked out revision 293.
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
## The text leading up to this was:

|diff -crB AstroMenace/AstroMenaceSource/Menu/Menu_Workshop_Shipyard.cpp AstroMenaceCheat/AstroMenaceSource/Menu/Menu_Workshop_Shipyard.cpp
|**\* AstroMenace/AstroMenaceSource/Menu/Menu_Workshop_Shipyard.cpp  2014-08-24 15:21:28.218120917 +0200
## |--- AstroMenaceCheat/AstroMenaceSource/Menu/Menu_Workshop_Shipyard.cpp 2014-08-22 13:48:59.947550000 +0200

File to patch: 
Skip this patch? [y] y
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 66
Perhaps you used the wrong -p or
###### 

can u make a new patch, which works with the stable version of openastronmanace? version 1.3.2? i am gentoo linux user and would like to use, but use on a version in git its not recommend, cuz it change quick.

**Comment by richelbilderbeek** [comment]
Thanks for the awesome bug report! I will look at it within a week. Unless you have fixed it yourself, of course :-)

**Comment by landscape69** [comment]
i have ineed found the culprit.

the path of the patching files are wrong. please modify this and the patch works fine. also the patch.sh dont work because of wrong path.

f.e.:

diff -crB AstroMenaceSource/Menu/Menu_Workshop_Weaponry.cpp AstroMenaceSource/Menu/Menu_Workshop_Weaponry.cpp
**\* AstroMenaceSource/Menu/Menu_Workshop_Weaponry.cpp   2014-08-24 15:21:28.222121020 +0200
--- AstroMenaceSource/Menu/Menu_Workshop_Weaponry.cpp   2014-08-22 13:51:05.989661000 +0200

---

**\* 119,150 ****

**Comment by richelbilderbeek** [comment]
I think I fixed it. You can do a `git pull` in the `AstroMenaceCheat` folder and then run `./patch.sh`. I also added that it installs the prerequisites I missed, so it will ask for your password. It asks to re-apply the patch, just press enter (means: no) all the time. Have fun and thanks for the big report. I will close the issue if you acknowledge it works correctly.

**Comment by landscape69** [comment]
no lcue what u did but, it dont solve the problem.

 U   .
Checked out revision 293.
patching file AstroMenace/AstroMenaceSource/Menu/Menu_Workshop_Shipyard.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] -R
Apply anyway? [n] y
Hunk #1 FAILED at 139.
1 out of 1 hunk FAILED -- saving rejects to file AstroMenace/AstroMenaceSource/Menu/Menu_Workshop_Shipyard.cpp.rej
patching file AstroMenace/AstroMenaceSource/Menu/Menu_Workshop_Weaponry.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file AstroMenace/AstroMenaceSource/Menu/Menu_Workshop_Workshop.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file AstroMenace/AstroMenaceSource/Object3D/SpaceShip/EarthSpaceFighter/EarthSpaceFighter.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] -R
Apply anyway? [n] 
Skipping patch.
22 out of 22 hunks ignored -- saving rejects to file AstroMenace/AstroMenaceSource/Object3D/SpaceShip/EarthSpaceFighter/EarthSpaceFighter.cpp.rej
CMake Error: The source directory "/home/cornix/Downloads/0" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: **\* No targets specified and no makefile found.  Stop.
./patch.sh: line 8: ./AstroMenace: Is a directory
./patch.sh: line 9: ./AstroMenace: Is a directory

just dont let patch ask anything. let it patch and print a message.

**Comment by richelbilderbeek** [comment]
The patch itself is not the error: if it asks you to redo the patching, you can (I think) assume it works. It is the making of the AstroMenace exectuable itself that was a problem. I updated the patch.sh file, perhaps it gives some nice feedback?

**Comment by landscape69** [comment]
ok all works now fine.

thanks for quick solution

**Comment by richelbilderbeek** [comment]
Excellent! Thanks for your help.
